import "./globals.css";
import { Cormorant } from "next/font/google";

const cormorant = Cormorant({ subsets: ["latin"], weight: "400" });

import Footer from "./components/Footer";
import NavAntiguo from "./components/NavAntiguo";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cormorant.className}>
        <NavAntiguo />
        {children}
        <Footer />
      </body>
    </html>
  );
}
