import "./globals.css";
import Footer from "./components/Footer";
import NavAntiguo from "./components/NavAntiguo";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-indigo-700 ">
        <NavAntiguo />
        {children}
        <Footer />
      </body>
    </html>
  );
}
